export type SearchCategory = 'page' | 'action' | 'setting' | 'admin' | 'guide'

export interface SearchItem {
  id: string
  title: string
  subtitle: string
  path?: string                   // navigate to this route
  category: SearchCategory
  keywords: string[]
  requiredPermissions?: string[]  // user needs ANY ONE of these; omit = visible to all
  guideId?: string                // if set, opens guide sub-view instead of navigating
}

export const SEARCH_REGISTRY: SearchItem[] = [
  // ── Pages ──────────────────────────────────────────────────────────────────
  {
    id: 'dashboard',
    title: 'Dashboard',
    subtitle: 'Overview, balances, recent activity',
    path: '/dashboard',
    category: 'page',
    keywords: ['home', 'overview', 'summary', 'balance', 'activity'],
  },
  {
    id: 'payments',
    title: 'Payments',
    subtitle: 'All payments — history and status',
    path: '/payments',
    category: 'page',
    keywords: ['transfer', 'send', 'wire', 'remit', 'transaction', 'history'],
    requiredPermissions: ['payments:view', 'payments:view_all', 'payments:create', 'payments:approve'],
  },
  {
    id: 'approval-queue',
    title: 'Approval queue',
    subtitle: 'Payments pending checker approval',
    path: '/payments/approval-queue',
    category: 'page',
    keywords: ['approve', 'checker', 'pending', 'review', 'queue'],
    requiredPermissions: ['payments:approve'],
  },
  {
    id: 'scheduled-payments',
    title: 'Scheduled payments',
    subtitle: 'Recurring and future-dated payments',
    path: '/payments/scheduled',
    category: 'page',
    keywords: ['recurring', 'schedule', 'future', 'automatic', 'standing order'],
    requiredPermissions: ['payments:view', 'payments:view_all', 'payments:create'],
  },
  {
    id: 'accounts',
    title: 'Accounts',
    subtitle: 'Currency accounts and balances',
    path: '/accounts',
    category: 'page',
    keywords: ['wallet', 'balance', 'usd', 'eur', 'gbp', 'currency', 'iban', 'ledger'],
    requiredPermissions: ['accounts:view'],
  },
  {
    id: 'beneficiaries',
    title: 'Beneficiaries',
    subtitle: 'Saved recipients for payments',
    path: '/beneficiaries',
    category: 'page',
    keywords: ['recipient', 'payee', 'bank', 'contact', 'counterparty'],
    requiredPermissions: ['beneficiaries:view'],
  },
  {
    id: 'fx-rates',
    title: 'FX rates',
    subtitle: 'Live exchange rates and quote history',
    path: '/fx-rates',
    category: 'page',
    keywords: ['exchange', 'rate', 'fx', 'currency', 'convert', 'quote', 'spread'],
  },
  {
    id: 'network',
    title: 'Network map',
    subtitle: 'Payment corridors and provider coverage',
    path: '/network',
    category: 'page',
    keywords: ['corridor', 'map', 'coverage', 'route', 'provider', 'country'],
  },
  {
    id: 'kyc',
    title: 'KYC / Verification',
    subtitle: 'Identity verification status and documents',
    path: '/kyc',
    category: 'page',
    keywords: ['kyc', 'kyb', 'identity', 'verify', 'compliance', 'document', 'passport'],
  },
  {
    id: 'statement',
    title: 'Account statement',
    subtitle: 'Downloadable account statements',
    path: '/reports/statement',
    category: 'page',
    keywords: ['statement', 'report', 'download', 'pdf', 'export', 'monthly'],
    requiredPermissions: ['reports:view'],
  },
  {
    id: 'transactions-report',
    title: 'Transactions report',
    subtitle: 'Full transaction history with filters',
    path: '/reports/transactions',
    category: 'page',
    keywords: ['report', 'transactions', 'history', 'export', 'csv', 'filter', 'date range'],
    requiredPermissions: ['reports:view'],
  },
  {
    id: 'reconciliation',
    title: 'Reconciliation',
    subtitle: 'Payment reconciliation and matched/unmatched entries',
    path: '/reports/reconciliation',
    category: 'page',
    keywords: ['reconcile', 'match', 'settle', 'discrepancy', 'audit'],
    requiredPermissions: ['reports:view'],
  },
  {
    id: 'assistant',
    title: 'AI assistant',
    subtitle: 'Ask questions about your payments and accounts',
    path: '/assistant',
    category: 'page',
    keywords: ['ai', 'chat', 'help', 'ask', 'question', 'assistant', 'bot'],
  },

  // ── Quick actions ───────────────────────────────────────────────────────────
  {
    id: 'new-payment',
    title: 'New payment',
    subtitle: 'Send a cross-border payment',
    path: '/payments/new',
    category: 'action',
    keywords: ['send', 'transfer', 'create', 'wire', 'remit', 'pay'],
    requiredPermissions: ['payments:create'],
  },
  {
    id: 'new-beneficiary',
    title: 'Add beneficiary',
    subtitle: 'Register a new payment recipient',
    path: '/beneficiaries/new',
    category: 'action',
    keywords: ['add', 'create', 'recipient', 'payee', 'bank', 'new'],
    requiredPermissions: ['beneficiaries:view'],
  },
  {
    id: 'new-scheduled',
    title: 'Schedule a payment',
    subtitle: 'Set up a recurring or future-dated payment',
    path: '/payments/scheduled/new',
    category: 'action',
    keywords: ['recurring', 'schedule', 'automatic', 'future', 'standing'],
    requiredPermissions: ['payments:create'],
  },
  {
    id: 'kyc-verify',
    title: 'Submit KYC documents',
    subtitle: 'Upload identity documents for verification',
    path: '/kyc/verify',
    category: 'action',
    keywords: ['upload', 'document', 'verify', 'id', 'passport', 'kyc', 'submit'],
  },

  // ── Settings ────────────────────────────────────────────────────────────────
  {
    id: 'profile',
    title: 'Profile settings',
    subtitle: 'Name, contact details, my role & permissions',
    path: '/settings/profile',
    category: 'setting',
    keywords: ['profile', 'name', 'email', 'phone', 'account', 'me'],
  },
  {
    id: 'mfa',
    title: 'Two-factor authentication',
    subtitle: 'Set up or manage TOTP MFA',
    path: '/settings/mfa',
    category: 'setting',
    keywords: ['mfa', '2fa', 'totp', 'authenticator', 'security', 'two factor', 'otp'],
  },
  {
    id: 'notifications',
    title: 'Notification preferences',
    subtitle: 'Email and in-app notification settings',
    path: '/settings/notifications',
    category: 'setting',
    keywords: ['notification', 'email', 'alert', 'push', 'preference'],
  },
  {
    id: 'theme',
    title: 'Theme & branding',
    subtitle: 'Logo, colours, company name',
    path: '/settings/theme',
    category: 'setting',
    keywords: ['theme', 'branding', 'logo', 'colour', 'color', 'design', 'white label'],
  },
  {
    id: 'users',
    title: 'User management',
    subtitle: 'Invite, suspend, and manage team members',
    path: '/settings/users',
    category: 'setting',
    keywords: ['user', 'invite', 'team', 'member', 'suspend', 'staff'],
    requiredPermissions: ['users:manage'],
  },
  {
    id: 'permissions',
    title: 'Roles & permissions',
    subtitle: 'Create and edit roles, assign permissions',
    path: '/settings/permissions',
    category: 'setting',
    keywords: ['role', 'permission', 'rbac', 'access', 'maker', 'checker', 'admin'],
    requiredPermissions: ['admin:config'],
  },
  {
    id: 'role-comparison',
    title: 'Compare roles',
    subtitle: 'Side-by-side permission matrix for all roles',
    path: '/settings/permissions/compare',
    category: 'setting',
    keywords: ['compare', 'role', 'matrix', 'permission', 'diff'],
    requiredPermissions: ['admin:config'],
  },
  {
    id: 'sub-clients',
    title: 'Sub-clients',
    subtitle: 'Manage sub-organisations under your account',
    path: '/settings/sub-clients',
    category: 'setting',
    keywords: ['sub-client', 'sub client', 'organisation', 'child', 'branch'],
    requiredPermissions: ['subclients:view'],
  },
  {
    id: 'feature-flags',
    title: 'Feature flags',
    subtitle: 'Enable or disable platform features per tenant',
    path: '/settings/features',
    category: 'setting',
    keywords: ['feature', 'flag', 'toggle', 'enable', 'disable', 'beta'],
    requiredPermissions: ['admin:features'],
  },

  // ── Admin ───────────────────────────────────────────────────────────────────
  {
    id: 'tenants',
    title: 'Tenants',
    subtitle: 'All client organisations on the platform',
    path: '/admin/tenants',
    category: 'admin',
    keywords: ['tenant', 'client', 'organisation', 'onboard', 'account'],
    requiredPermissions: ['admin:config'],
  },
  {
    id: 'kyc-queue',
    title: 'KYC review queue',
    subtitle: 'Approve or reject KYC applications',
    path: '/admin/kyc-queue',
    category: 'admin',
    keywords: ['kyc', 'review', 'queue', 'approve', 'reject', 'compliance'],
    requiredPermissions: ['admin:config', 'admin:kyc'],
  },
  {
    id: 'manual-payments',
    title: 'Manual payment queue',
    subtitle: 'Payments awaiting ops team processing',
    path: '/admin/manual-payments',
    category: 'admin',
    keywords: ['manual', 'queue', 'ops', 'process', 'pending'],
    requiredPermissions: ['admin:config'],
  },
  {
    id: 'all-payments',
    title: 'All payments (admin)',
    subtitle: 'Platform-wide payment ledger across all tenants',
    path: '/admin/payments',
    category: 'admin',
    keywords: ['all', 'payments', 'platform', 'global', 'admin'],
    requiredPermissions: ['admin:config'],
  },
  {
    id: 'provider-config',
    title: 'Provider configuration',
    subtitle: 'Payment provider routing and corridor rules',
    path: '/admin/providers',
    category: 'admin',
    keywords: ['provider', 'zoqq', 'manual', 'corridor', 'routing', 'config'],
    requiredPermissions: ['admin:config'],
  },
  {
    id: 'global-fees',
    title: 'Global fee rules',
    subtitle: 'Platform-wide default fee schedule',
    path: '/admin/global-fees',
    category: 'admin',
    keywords: ['fee', 'global', 'charge', 'pricing', 'rule', 'schedule'],
    requiredPermissions: ['admin:config'],
  },
  {
    id: 'on-behalf',
    title: 'Payment on behalf',
    subtitle: 'Submit a payment on behalf of a client',
    path: '/admin/payments/on-behalf',
    category: 'admin',
    keywords: ['on behalf', 'behalf', 'submit', 'admin', 'client payment'],
    requiredPermissions: ['admin:config'],
  },

  // ── Guides ──────────────────────────────────────────────────────────────────
  {
    id: 'guide-provider-resolution',
    title: 'Provider resolution order',
    subtitle: 'How RemitX picks a payment provider for each corridor',
    category: 'guide',
    keywords: ['provider', 'routing', 'corridor', 'zoqq', 'manual', 'resolution', 'fallback', 'order'],
    guideId: 'provider-resolution',
  },
  {
    id: 'guide-maker-checker',
    title: 'Maker-checker workflow',
    subtitle: 'How dual-control payment approval works',
    category: 'guide',
    keywords: ['maker', 'checker', 'approval', 'workflow', 'dual control', 'two person', 'authorise'],
    guideId: 'maker-checker',
  },
  {
    id: 'guide-fx-quote',
    title: 'FX quote & rate lock',
    subtitle: 'How exchange rate quotes are locked and expire',
    category: 'guide',
    keywords: ['fx', 'quote', 'rate', 'lock', 'expire', 'ttl', 'exchange'],
    guideId: 'fx-quote',
  },
  {
    id: 'guide-kyc',
    title: 'KYC / KYB process',
    subtitle: 'Identity verification stages and requirements',
    category: 'guide',
    keywords: ['kyc', 'kyb', 'verify', 'identity', 'document', 'compliance', 'approved', 'expired'],
    guideId: 'kyc',
  },
  {
    id: 'guide-fees',
    title: 'Fee categories explained',
    subtitle: 'All six fee types and how they are resolved',
    category: 'guide',
    keywords: ['fee', 'charge', 'activation', 'iban', 'maintenance', 'amc', 'transaction'],
    guideId: 'fees',
  },
  {
    id: 'guide-roles',
    title: 'Roles & permission model',
    subtitle: 'Built-in roles, what each can do, and how to customise',
    category: 'guide',
    keywords: ['role', 'permission', 'super admin', 'client admin', 'maker', 'checker', 'rbac'],
    guideId: 'roles',
  },
]

export const CATEGORY_META: Record<SearchCategory, { label: string; order: number }> = {
  action:  { label: 'Quick actions', order: 0 },
  page:    { label: 'Pages',         order: 1 },
  setting: { label: 'Settings',      order: 2 },
  admin:   { label: 'Admin',         order: 3 },
  guide:   { label: 'Guides',        order: 4 },
}
